<?xml version="1.0"?>
<package format="3">

  <name>d455_interfaces</name>
  <version>0.0.1</version>

  <description>Custom interfaces for the D455 perception stack.</description>

  <maintainer email="radar@todo.todo">radar</maintainer>

  <license>Apache-2.0</license>

  <!-- Build -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <!-- Message dependencies -->
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>

  <!-- Runtime -->
  <exec_depend>rosidl_default_runtime</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

  <member_of_group>rosidl_interface_packages</member_of_group>

</package>
